name: CI/CD Pipeline Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          chmod +x mvnw
          ./mvnw clean install

      - name: Run Spring Boot App
        run: |
          nohup ./mvnw spring-boot:run &
          sleep 10

      - name: Verify Application Running
        run: |
          curl -f http://localhost:8082/api/hello || exit 1
